### ISSUE TITLE
Website Structure

### ISSUE THREAD

**Issue by guli333** [alirezamika/autoscraper#58]
Hello! Thank you so much for sharing your work!

I wanted to ask, if i trained my model on some website, then this website will change the website structure and styling , will it still work? Can I get the same data? or I will be needed to re-train it again?

**Comment by guli333** [comment]
One more question, can I somehow get the whole information that is on the page? or I need to paste everything I want into 'wanted_list'?

**Comment by alirezamika** [comment]
Hi there,

If the changes are small like small changes in tag names, the scraper can still get the result by adjusting the `attr_fuzz_ratio` parameter. Otherwise you should probably re-train it.

If the items you want to get can be specified by regex, you can use regex instead of copying all of them.
